[project]
name = "wordy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=6.0.2",
    "pillow>=12.1.0",
    "pyglossary>=5.2.1",
    "pyinstaller>=6.18.0",
    "pyqt6>=6.10.2",
    "pyqt6-webengine>=6.10.0",
]
